[setting.GHO_max_collateral_limit]
defaultValue = "<%= parseEther(String(50_000_000)) %>"

[setting.GHO_issuance_ratio]
defaultValue = "<%= parseEther('1.25') %>"

[setting.GHO_liquidation_ratio]
defaultValue = "<%= parseEther('1.05') %>"

[setting.GHO_liquidation_reward]
defaultValue = "<%= parseEther('1') %>"

[setting.GHO_min_delegation]
defaultValue = "<%= parseEther('100') %>"

[invoke.CoreProxy_configureCollateral_GHO]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.CoreProxy_configureCollateral_GHO.args]]
tokenAddress = "<%= settings.gho_address %>"
oracleNodeId = "<%= extras.GHO_oracle_id %>"
issuanceRatioD18 = "<%= settings.GHO_issuance_ratio %>"
liquidationRatioD18 = "<%= settings.GHO_liquidation_ratio %>"
liquidationRewardD18 = "<%= settings.GHO_liquidation_reward %>"
minDelegationD18 = "<%= settings.GHO_min_delegation %>"
depositingEnabled = true

[invoke.CoreProxy_setPoolCollateralConfiguration_GHO]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= extras.spartan_council_pool_id %>"]
func = "setPoolCollateralConfiguration"
args = [
    "<%= extras.spartan_council_pool_id %>",
    "<%= settings.gho_address %>",
    { collateralLimitD18 = "<%= settings.GHO_max_collateral_limit %>", issuanceRatioD18 = 0 },
]
